- .github/workflows/check_images_x_region.sh
- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
A couple fixes for earlier mistakes, as always.
> GHA Adjustments

- .github/workflows/check_images_x_region.sh
- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
And use tagged version of configure-aws-credentials
GitHub Action Changes
N/A
No
**Checklist**
> Use updated version of check_images_x_region

- .github/workflows/tag-latest.yml
Incorrect tag version
**Checklist**
> Fix aws-credentials version

- .github/workflows/release-images.yml
> Fix aws credentials in main build

- build/python/backend/requirements.txt
- src/python/strelka/scanners/scan_ole.py
- src/python/strelka/scanners/scan_pdf.py
- src/python/strelka/scanners/scan_vba.py
> Suppress Unnecessary Logs & Fix an Undefined Reference

- build/configs/scanners.yaml
Scan html files for URLs
N/A, low risk.
**Checklist**
> Scan html files for URLs

- build/configs/scanners.yaml
Ensures ExifTools is run on any files that it may be applicable to.
N/A
**Checklist**
> Run ExifTools for several other word doc types

- build/configs/scanners.yaml
Enables the Libarchive scanner
Tested with a couple of ISO files
N/A
**Checklist**
> Include Libarchive (ISO) support

- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
Had flagged vulnerabilities and we're not using this.
> Remove MMRPC Build

- build/python/backend/Dockerfile
Hopefully fix some flagged vulnerabilities. `docker scan` didn't pickup these vulnerabilities so unfortunately I can't validate that they're resolved, but the update instructions associated with the CVEs are pretty clear.
Validated build still works. It's unlikely these would effect scanning, but it'll be validated before release.
N/A
**Checklist**
> Resolve flagged vulnerabilities

- src/go/cmd/strelka-frontend/main.go
Support receiving gzip grpc messages.
Validated that a gzip client request did not work without this, and does with this.
N/A
**Checklist**
> Add import for gzip support

- build/python/backend/Dockerfile
Mitigate libsepol vulnerabilities
`docker scan` identified vulnerabilities in previous version of image, and shows that no `libsepol` vulnerabilities exist in this image.
N/A
**Checklist**
> Mitigate libsepol vulnerabilities

- build/configs/scanners.yaml
- src/python/strelka/scanners/scan_rtf.py
> Enable RTF, LNK, Email Scanners + fix RTF Scanner bug

- src/python/strelka/scanners/scan_rtf.py
> Avoid using invalid rtf property (server)

- build/configs/taste.yara
- build/python/backend/Dockerfile
- configs/python/backend/taste/taste.yara
https://www.notion.so/sublimesecurity/Strelka-not-returning-javascript-identifiers-from-some-HTML-files-01e20943af9a4443925eb253068857ee
This PR adds the `let` keyword to the javascript yara rule. The script in the ticket was just 
```js
let url = \"https://badlinkgoeshere\";//Enter live link to be loaded;"," 
location.replace(url);","
```
ES6 allows for the `let` keyword rather than `var` which is common in most javascript.
Before the change:
```
{"file":{"depth":1,"flavors":{"mime":["text/plain"]},"name":"script_0","scanners":["ScanEntropy","ScanHash","ScanStrings","ScanUrl"],"size":132,"source":"ScanHtml","tree":{"node":"2403a18d-11b9-4f93-a3d7-53098bb892aa","parent":"a761fd62-9805-49ff-8670-d235ea87b809","root":"a761fd62-9805-49ff-8670-d235ea87b809"}},"request":{"attributes":{"filename …
```
> Adds  keyword to js scanner to scan es6 compliant js

- build/configs/scanners.yaml
Just expands a scanner.
N/A
N/A
**Checklist**
> Add MIME form of HTML flavor to Strings scanner

- build/configs/scanners.yaml
_This is all @morriscode's handywork, I take no credit! 😄 We're just going through the paces of making PRs together._
Added PDF files to Strings and Exiftools scanner.
Note: still need to test.
Sample of strings output on PDF File:
```
pdf:{} 1 item
strings:{} 1 item
strings:[] 5422 items
0:%PDF-1.4
1:1 0 obj
2:<</Type/XObject/Subtype/Image/Width 842/Height 572/Length 490/ColorSpace/DeviceGray/BitsPerComponent …
```
> Add PDF flavor to ScanStrings

- src/go/cmd/strelka-frontend/main.go
Redis keys were not being set when in.Data was empty.
> properly handle empty yara data

- src/go/api/strelka/README.md
> Add docs for compiling protobufs

- build/python/backend/Dockerfile
Addresses a vulnerability
Built and tested in consuming service.
**Checklist**
> Update Ubuntu to 22.10

- configs/python/backend/backend.yaml
Adding 'application/zip' and 'zip_file' to scanners.yml. This will allow us to know things about the contents of the zip in the event of extraction failure/timeouts. It will also allow rule creation on zip metadata such as uncompressed size, create date, author, required zip versions, etc.
modified ./configs/backend/scanners.yaml in my local sublime-platform instance to the above specifications. Tested multiple zip files for expected output.
```exiftool:{} 6 items
fields:[] 20 items
0:{} 2 items
key:SourceFile
value:/dev/shm/tmplmlf7n4k
1:{} 2 items
key:ExifToolVersion
value:12.44
2:{} 2 items
key:FileName
value:tmplmlf7n4k
3:{} 2 items
key:Directory
value:/dev/shm
4:{} 2 items
key:FileSize
value:660 kB
5:{} 2 items …
```
> Adding application/zip and zip_file to backend.yaml

- .github/workflows/release-images.yml
> Replace crazy-max docker meta with docker official

- src/python/strelka/scanners/scan_yara.py
Use the timeout option of `.match` set to the remaining time we have.
Ran standard tests + also including logging to validate that we're dealing with seconds to seconds.
N/A
**Checklist**
> Use yara.match timeout

- build/configs/scanners.yaml
Reverts sublime-security/strelka#67
> Revert "Drop ScanQR from config"

- src/python/strelka/scanners/scan_qr.py
Updates the ScanQR URL regex to be super permissive
> Updating URL regex for QR scanner

- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
> Update configure AWS credentials

- .github/workflows/check_images_x_region.sh
> X-Region check new regions

- .github/workflows/build_strelka_on_push.yml
I think this will allow the actions to run from forks. This will cause the build to run using the merged contents, which is fine.
N/A
> Change Push Build to on pull_request

- .github/workflows/check_images_x_region.sh
> Add ap-southeast-2 to x-region checks

- build/configs/scanners.yaml
- build/python/backend/requirements.txt
- src/python/strelka/scanners/scan_macho.py
Update and enable Macho scanner
Most changes just taken from upstream.
Tested in upstream.
N/A
> Enable and Upgrade MachO Scanner

- build/configs/scanners.yaml
Just updating the scan config accordingly
Did not
None
> Add ScanURL to text/calendar files

- build/configs/scanners.yaml
Added `application/ics` where `text/calendar` appears to ensure full coverage.
Did not test.
> Adding additional calendar invite type

- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
Gov Cloud support!
N/A, I have to test this by creating a release. But I've made same/similar changes in other repos so if there's any issues it'll just be typo sort of thing.
N/A
> Publish images to AWS GovCloud

- .github/workflows/release-images.yml
Fix copy/paste mistake in release workflow
N/A
> Fix copy/paste mistake in release workflow

- build/configs/scanners.yaml
Added `image/bmp` to the ScanQr flavors list.
> Adding additional BMP flavor for ScanQR

- .github/workflows/release-images.yml
- .github/workflows/tag-latest.yml
Change target GovCloud region to `us-gov-west-1` instead of `us-gov-east-1`
> Change gov to west

- .github/workflows/release-images.yml
> Use GitHub ARM runners

- build/configs/scanners.yaml
Adds scanning of GIFs to OCR.
Validated by @zoomequipd
> Add GIFs to ScanOCR

- build/go/fileshot/Dockerfile
- build/go/filestream/Dockerfile
- build/go/frontend/Dockerfile
- build/go/manager/Dockerfile
- build/go/oneshot/Dockerfile
- go.mod
- go.sum
> Upgrade to go 1.21.5

- build/configs/scanners.yaml
Added `svg_file` to scanner positives where `xml_file` was as well.
> Adding svg_file to scanners

- build/configs/scanners.yaml
Fixing TIFF MIME type change from #113 
Didn't.
> Changing back to image/tiff

- src/go/pkg/rpc/rpc.go
https://app.slack.com/client/TCHN716NQ/C088Z8M2A49
> Remove min

- .github/workflows/release-images.yml
https://www.notion.so/sublimesecurity/GitHub-Actions-Ubuntu-20-04-sunset-1a004655fc9d8018b776c64b47f12cf1?pvs=4
> Upgrade all GHA from Ubuntu 20.04 to latest.

- build/docker-compose.yaml
- build/go/fileshot/Dockerfile
- build/go/filestream/Dockerfile
- build/go/frontend/Dockerfile
- build/go/manager/Dockerfile
- build/go/oneshot/Dockerfile
- go.mod
Upgrade to Go 1.24
https://www.notion.so/sublimesecurity/Go-1-24-upgrade-strelka-19704655fc9d80969c73dabdadac026f?pvs=4
https://www.notion.so/sublimesecurity/Upgrade-Go-to-1-24-19704655fc9d81ec84f8ce98e94b7642?pvs=4
**Checklist**
> Upgrade to Go 1.24

- build/configs/scanners.yaml
- src/python/strelka/scanners/scan_doc_images.py
Adds a new scanner that extracts images from `.doc` files.
Made changes, rebuilt backend Docker container, tested on local Sublime instance
**Checklist**
> Adding image extraction for .doc files
