.github/workflows/release-images.yml
.github/workflows/tag-latest.yml

The docker files pull a lot of dependencies which make them
susceptible to transiently breaking. It'll be important that
we test images adequately before "releasing". Since the major/minor
and major tags would update immediately this could cause a new
image to be consumed before any testing. If we need these tags
we should move them to the update latest workflow.
Of course we can also put more effort into making the build reliable,
but that's more involved.

Only tag full version number

---

build/python/backend/Dockerfile

* Twice we've seen a build w/ JTR apparently unstable.
* It's unclear if this is a build issue, or a result of grabbing
a bad version (as we were just grabbing the repo head).
* This ensures we grab the same commit, so if we continue to see
issues we can go from there.
* There are no even halfway recent tags so the commit is arbitrary.
* Also changes the repo from magnumripper/JohnTheRipper to openwall/john
as that's where the old repo forwards to.
* And grab a single commit to speed things up (239 MB -> 140 ish MB).
Validated that intermittently failing test is passing (w/ cleared caches). This doesn't guarantee the issue is fixed, but at the very least nothing is worse.
**Checklist**

Use a specific version of JTR

---

src/python/strelka/scanners/scan_vba.py

It turns out this requires an `__enter__` method which vba parser
doesn't implement (and my IDE doesn't know about...).
I thought I'd tested this but I hadn't. Luckily I did before tagging
latest.
Validated that our CI tests pass against this image (they broke with the earlier change/v0.3.4 release). Also validated separately that the changes to scan_ole are hit so that usage of `with` is Ok.
**Checklist**

Revert earlier change to use with

---

src/go/cmd/strelka-frontend/main.go
src/python/bin/strelka-backend

We observed the 250ms floor latency, and according to scan times in
the Strelka response it looks like it's common for this to be mostly
wait time. The 250ms floor was when there are many backends, but with fewer
backends it was common to be closer to 500ms because of the 250ms poll time
on the BE.
Using long polling on both sides ensures things are about as fast as they can be, and probably
results in less load on redis in steady state.
Using small files that evaluated very fast I found that the latency was reduced from 250-500ms to ~20 ms. Large files didn't behave any differently.
N/A
**Checklist**

Task Send & Receive Long Polling

---

src/go/cmd/strelka-frontend/main.go

With the change to BLPOP an err returned by redis will cause an immediate retry/loop. This isn't the best behavior because any persistent errors will result in an infinite loop. Additionally nothing in this loop respects context cancellation, which presumably allows these occurrences to just build up (I'm not sure if anything will cause them to be killed eventually, but I'm not sure what could).
Validated everything still works as expected during normal conditions, and I've validated the looping behavior with context cancellation.
N/A
**Checklist**

Prevent fast iterations over err + respect ctx cancellation

---

build/python/backend/requirements.txt
src/python/strelka/scanners/scan_ocr.py

Looks like the new base image pulls in Python 3.10, but the `python-docx` package broke because Python makes breaking changes to its stdlib within a minor version? :shameshame:
I updated oletools to the latest as well, and right stripped output from the OCR file.
Ran and tweaked backend tests.
**Checklist**

Fix python-docx to work with python 3.10

---

build/configs/scanners.yaml
src/python/strelka/scanners/scan_zip.py

* Fix bug with encrypted flag (only worked if first file in manifest wasn't a folder)
* Always return all contained paths
* Return files that were attempted
Tested in consumer

Limit scanner timeouts, improve zip scanner

---

src/go/cmd/strelka-frontend/main.go
src/python/bin/strelka-backend
src/python/strelka/scanners/scan_yara.py

Scan extracted files with custom yara

---

configs/python/backend/rules.yara

In local dev, this matches every message and can be very confusing. There's no reason to keep it.
Ingest messages with a rule active which looks for `len(.scan.yara.matches) > 0` and no other rules ... the message should not flag.
N/A
**Checklist**
N/A

Remove default signature

---

build/configs/scanners.yaml
build/configs/taste.yara

Added a YARA flavour to detect Microsoft Onenote (`.one`) files, and added the flavour to the ScanStrings scanner.
Added flavour and scanner rule in my environment, and ran an email with an attached `.one` file. `binexplode` returned expected results.
```json
"result": [
[
{
"depth": 0,
"flavors": {
"mime": "application/octet-stream",
"yara": [
"onenote_file"
]
},
"size": 13504,
"name": "onenote_one_embedded_hta_rtlo.one",
"extension": "one",
"node_id": "bfce71aa-3f9f-4a0f-8785-6e7f4bb7b59f",
"scan": {
"entropy": {
"entropy": 3.2809219605231594
},
"hash": {
"md5": "028bf224490a965c0e70ab5f81269941",
"sha1": "016fbe544de546bb53ef1f25b75f0f65d70208a1",
"sha256": …
```

Adding Onenote rule & scanner

---

build/configs/scanners.yaml

Reverts sublime-security/strelka#43
Appeared to cause timeouts because the strings inside PDF are often a bunch of short ASCII garbage strings. We can enable this again in the future, and prune out random ASCII sequences from that list. TBD.

Revert "Add PDF flavor to ScanStrings"

---

build/configs/scanners.yaml

`configs/python/backend/backend.yaml` isn't what's used in our fork. `build/configs/scanners.yaml` is what we actually respect (it's built into our images).

Follow up to #55 (we have two scanner configs)

---

build/python/backend/Dockerfile
build/python/backend/requirements.txt

Build times were crazy slow for ARM64 because there wasn't a precompiled wheel for `lief` in PyPi for Python3.10 + ARM64! For this specific combination, I ran `python3 -m pip3 wheel lief==0.12.3` and the compiled `.whl` file is uploaded somewhere these builds can reach.
Built successfully with Apple Silicon locally, and confirmed the architecture is still linux/arm64.

Use precompiled wheel for ARM64 lief

---

src/python/strelka/scanners/scan_yara.py

`yara-python` interestingly requires an integer here.
Fixes:

Convert timeout to integer using math.ceiling

---

build/configs/scanners.yaml

Drop `ScanQR` from scanners config, because it adds unnecessary time and isn't used for any rules. We can always bring it back, and revisit how to be more selective then.

Drop ScanQR from config

---

build/configs/scanners.yaml
configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_ocr.py

Adds the ability to convert PDF documents into PNG images of their first page. This is controlled by the `pdf_to_png` option.

Convert PDF to PNG before running OCR

---

README.md
build/python/backend/requirements.txt
src/python/strelka/scanners/scan_ocr.py

Update muPDF so we can use some new functionality, this lets us manually override the default DPI of 72 and gives better accuracy in OCR output.

Set DPI when convering PDF -> PNG for OCR

---

build/python/backend/Dockerfile

Use `ubuntu22.04` since it's LTS and the dockerhub image [is still maintained](https://hub.docker.com/_/ubuntu/tags?page=1&name=22). We can't build 22.10 anymore because some ubuntu repositories are broken. We could in theory fix those, but I'd rather figure out 23.04.
I would love to update to 23.04, but that goes from Python 3.10 -> Python 3.11 and they keep making breaking ecosystem changes. This unblocks us and we can figure that out later.
Mostly supersedes #76, assuming we don't care to solve new Python 3.11 issues.

Switch to ubuntu:22.04

---

README.md
build/python/backend/requirements.txt
src/python/strelka/scanners/scan_ocr.py

Looks like there were some regressions introduced in the update to `PyMuPDF`.
I'm going to revert this while I investigate
Reverts sublime-security/strelka#74

Revert "Set DPI when convering PDF -> PNG for OCR"

---

build/configs/scanners.yaml
configs/python/backend/backend.yaml

Added `image/webp` to usual image scanners to account for a detection gap.
Ran a local instance with webp scanning enabled and it returned expected results.

Adding webp to strelka scanners

---

src/python/strelka/scanners/scan_ocr.py

This was deprecated a long time ago and is safe to remove now. Removes JSON bloat and is completely redundant with `.scan.ocr.raw`, but worse.

Drop .scan.ocr.text output

---

README.md
src/python/strelka/scanners/scan_ocr.py

It really doesn't make sense to have trailing whitespace for a line in OCR, so we're dropping it.

Cleanup trailing whitespace in OCR

---

build/python/backend/requirements.txt

Drop this dependency which is not needed. It was added in the upstream accidentally and also removed since it was unused.
- https://github.com/target/strelka/pull/168/files
- https://github.com/target/strelka/commit/b14526ae4d56c187e3a6f15f3513b418d0942f2e

Drop unused dependency

---

build/configs/scanners.yaml

TL;DR: some attached HTML files come back with both `javascript_file` and `html_file` which stops us from pulling out URLs. This should fix that.

Removing javascript_file negative from ScanUrl

---

.github/workflows/release-images.yml

https://github.com/sublime-security/strelka/actions/runs/11134337602
The release workflow isn't picking up a runner. I had to dig a little but it turns out our customized runners are part of our default group, which isn't accessible to public repos. GH cautions about sharing public/private runners, although I think it's really more about self hosted runners which might have additional permissions/networking/etc. I didn't see any drawback so I just created a new runner group which can be allowed for public repos and created identical runners within the group. This change just references those new runners.
None, I could test in PR but keeping it simple since I'm pretty sure this is all that's required. If this still doesn't work I'll …

Use public runner group runners

---

build/python/backend/requirements.txt

Updates `idna` python library to the latest, as well as `requests` which uses it. This was listed a medium vuln, but the customer has it as a high.
Before:
After:

Update idna python lib

---

build/configs/scanners.yaml

Adding `image/svg+xml`, as yara tasting can sometimes miss on SVGs.

Adding 'image/svg+xml'

---

build/configs/scanners.yaml
configs/python/backend/backend.yaml
src/python/strelka/scanners/scan_ocr.py
src/python/strelka/scanners/scan_pdf.py
src/python/strelka/scanners/scan_qr.py

Update QR scanning to use the same logic as OCR to convert a PDF to a PNG (we'll switch this to TIFF in the future).
Also 
Validated end-to-end for a PDF that this works as expected.

Convert PDFs to PNGs before scanning

---

build/configs/scanners.yaml
src/python/strelka/scanners/scan_pdf.py

This changes our behavior from extracting objects from PDFs to just taking images from a PDF to then run OCR and other scanners.
Ongoing, ping me

Convert PDFs to PNGs & skip other PDF object extraction

---

go.mod

Upgrade to go 1.24.2 (CVE-2025-22871)
https://www.notion.so/sublimesecurity/Upgrade-to-Go-1-24-2-CVE-2025-22871-1c804655fc9d800499aeca58e70398a2?pvs=4

Upgrade to go 1.24.2 (CVE-2025-22871)

---

src/go/cmd/strelka-frontend/main.go
src/go/cmd/strelka-manager/main.go
src/python/bin/strelka-backend

Handle `SIGINT` signals in all services to allow auto scaling down gracefully.
* Updated my local docker compose to use SIGINT, not SIGKILL for shutdown.
* Tested regular idle shutdown
* Exited w/ status code `0` after a few seconds (due to blocking `bzpopmin` call)
* Validated requeing behavior: 
* Initiated shutdown via docker
* Sent a task to the Strelka queue
* Saw `Received task after shutdown signal, re-queuing` message, and then a clean shutdown
* Restarted backend container
* Task was picked up and processed.
We generally send tasks with a 1 minute timeout, so we'll want to allow a full minute for graceful shutdown (probably plus a little buffer).
I simply just validated that the signal was received and resulted in shutdown …

Gracefully shutdown on SIGINT for FE/BE/Manager

---

build/configs/scanners.yaml
build/configs/taste.yara
src/python/strelka/scanners/scan_mht.py

Adds support for MHT file exploding and metadata generation via a `ScanMht` scanner.  This scanner uses an python builtin `email` for the parsing of the MHT file
This required updating of the taste yara rule for `mhtml_file` to account for the observed file format which lacked the "archive_text" condition. 
The ScanMht scanner does introduce new fields into the strelka output that might require changes within other sublime-platform elements.  Specially there are objects in the json output of Strelka (below) which are not represented within the output of file.explode within the product. Adding these elements to the output of file.explode is not a blocking requirement. 
The below JSON is the output of strelka as a result of the MHT file. 
```
{
"mht": {
"boundary": …
```

Add ScanMht scanner

---

build/python/backend/Dockerfile

Updates the zbar package to 0.23.93 by installing the package directly from a pre-built release. There are two critical CVEs that are tied to version 0.23.92:
* https://ubuntu.com/security/CVE-2023-40890 - fixed with Ubuntu Pro in 22.04, does not affect 24.04
* https://ubuntu.com/security/CVE-2023-40889 - fixed with Ubuntu Pro in 22.04, does not affect 24.04
However, 0.23.92 is the latest package version available for 22.04 when installing from apt (the fix with Ubuntu Pro is not generally available). This change installs the next version with the CVEs addressed.
This update also addresses https://ubuntu.com/security/CVE-2024-3596 by specifying krb5 package numbers that include fixes for the CVE for all packages currently marked as having a critical vulnerability. …

Address critical CVEs with backend image

---

build/python/backend/requirements.txt

Updates lief version to 0.15.1, to address https://github.com/sublime-security/strelka/security/dependabot/4. Dependabot couldn't create the PR itself - my guess is because of the old logic we had regarding lief versions and deployments. However, lief now supports arm64, so I've removed the deployment-specific logic and put the version to 0.15.1 (which addresses the vulnerability).
Validated with local rebuild, will also validate with CI
**Checklist**

Updates lief version to address security vulnerability

---

build/python/backend/requirements.txt

This reverts commit 5f6b5ea4a4df082570be3934114a6a4aaafd9ddc.
There was a test not exercised by CI when updating Lief to address a vulnerability. This reverts that change.
Reran strelka file tests - specifically, the Mach0 file test which fails with the Lief upgrade.
**Checklist**

Revert "Updates lief version to address security vulnerability (#134)"

---

build/configs/scanners.yaml
src/python/strelka/scanners/scan_strings.py

Add option for when a file is all plain text, returning the text as a single raw string. The existing scan strings scanner produces an output array of strings. This proposed change introduces a new field `.raw` which produces the output as a single string. 
This functionality is limited to when the output can be successfully decoded in the resulting object is a `str` instance.
**Image Creation**
- via git checked out the test branch within the sublime-security fork of strelka
- built a new strelka image from that repo
- updated the docker-compose within sublime-platform repo to use the local image for the sublime_strelka_backend service
- ran a docker compose up -d from sublime-platform
observed the recreated containers running the …

Adding .raw output to scanned strings
